"""Offline PostgreSQL DDL generator for the ERP schema inventory.

This module reads the checked-in schema compatibility report and writes generated
PostgreSQL DDL artifacts. It never opens a database connection and never deploys
schema.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
import re


REPO_ROOT = Path(__file__).resolve().parent
DEFAULT_INVENTORY_REPORT = REPO_ROOT / "reports" / "postgres_schema_compatibility.md"
DEFAULT_SQL_OUTPUT = REPO_ROOT / "reports" / "postgres_generated_schema.sql"
DEFAULT_SUMMARY_OUTPUT = REPO_ROOT / "reports" / "postgres_generated_schema_summary.md"

TYPE_MAPPINGS = {
    "INTEGER PRIMARY KEY AUTOINCREMENT": "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    "INTEGER PRIMARY KEY": "BIGINT PRIMARY KEY",
    "TEXT": "TEXT",
    "REAL": "NUMERIC(18,2)",
    "CURRENT_TIMESTAMP": "CURRENT_TIMESTAMP",
}

BOOLEAN_CANDIDATE_COLUMNS = {
    "is_active",
    "is_locked",
    "is_voided",
    "is_cleared",
    "is_enabled",
    "posting_allowed",
    "control_account",
    "allow_manual_posting",
    "opening_posted",
}

UNSUPPORTED_SOURCE_PATTERNS = (
    "PRAGMA",
    "sqlite_master",
    "sqlite_sequence",
    "INSERT OR IGNORE",
    "BEGIN IMMEDIATE",
    "AUTOINCREMENT",
)


@dataclass
class ForeignKeyInventory:
    column: str
    references_table: str
    references_column: str
    on_delete: str = ""


@dataclass
class IndexInventory:
    name: str
    definition: str = ""


@dataclass
class TableInventory:
    name: str
    sqlite_sql: str
    indexes: list[IndexInventory] = field(default_factory=list)
    foreign_keys: list[ForeignKeyInventory] = field(default_factory=list)


@dataclass
class GeneratedSchemaPlan:
    sql: str
    summary: str
    table_count: int
    index_count: int
    foreign_key_count: int
    unsupported_constructs: list[str]
    manual_review_items: list[str]
    dependency_cycles: list[list[str]] = field(default_factory=list)
    ordered_tables: list[str] = field(default_factory=list)


def _strip_code_fence(sql_block: str) -> str:
    return sql_block.strip().rstrip(";")


def _parse_index_names(section: str) -> list[IndexInventory]:
    match = re.search(r"\*\*Indexes:\*\*\s*(.+)", section)
    if not match:
        return []
    return [IndexInventory(name=name) for name in re.findall(r"`([^`]+)`", match.group(1))]


def _parse_foreign_keys(section: str) -> list[ForeignKeyInventory]:
    foreign_keys: list[ForeignKeyInventory] = []
    for column, table, ref_column, on_delete in re.findall(
        r"- `([^`]+)` \u2192 `([^`.]+)\.([^`]+)` \(on_delete=([^)]+)\)",
        section,
    ):
        foreign_keys.append(
            ForeignKeyInventory(
                column=column,
                references_table=table,
                references_column=ref_column,
                on_delete=on_delete,
            )
        )
    return foreign_keys


def parse_schema_compatibility_report(report_text: str) -> list[TableInventory]:
    tables: list[TableInventory] = []
    for match in re.finditer(r"^### `([^`]+)`\s*(.*?)(?=^### `|\Z)", report_text, flags=re.MULTILINE | re.DOTALL):
        table_name = match.group(1)
        section = match.group(2)
        sql_match = re.search(r"```sql\s*(.*?)\s*```", section, flags=re.DOTALL)
        if not sql_match:
            continue
        tables.append(
            TableInventory(
                name=table_name,
                sqlite_sql=_strip_code_fence(sql_match.group(1)),
                indexes=_parse_index_names(section),
                foreign_keys=_parse_foreign_keys(section),
            )
        )
    return sorted(tables, key=lambda table: table.name)


def _table_dependencies(table: TableInventory, table_names: set[str]) -> set[str]:
    return {
        foreign_key.references_table
        for foreign_key in table.foreign_keys
        if foreign_key.references_table in table_names and foreign_key.references_table != table.name
    }


def detect_dependency_cycles(tables: list[TableInventory]) -> list[list[str]]:
    table_map = {table.name: table for table in tables}
    table_names = set(table_map)
    visiting: set[str] = set()
    visited: set[str] = set()
    stack: list[str] = []
    cycles: list[list[str]] = []
    cycle_keys: set[tuple[str, ...]] = set()

    def visit(table_name: str) -> None:
        if table_name in visited:
            return
        if table_name in visiting:
            cycle_start = stack.index(table_name)
            cycle = stack[cycle_start:] + [table_name]
            key = tuple(sorted(set(cycle)))
            if key not in cycle_keys:
                cycle_keys.add(key)
                cycles.append(cycle)
            return

        visiting.add(table_name)
        stack.append(table_name)
        for dependency in sorted(_table_dependencies(table_map[table_name], table_names)):
            visit(dependency)
        stack.pop()
        visiting.remove(table_name)
        visited.add(table_name)

    for table_name in sorted(table_names):
        visit(table_name)
    return cycles


def order_tables_by_dependencies(tables: list[TableInventory]) -> list[TableInventory]:
    table_map = {table.name: table for table in tables}
    table_names = set(table_map)
    remaining = set(table_names)
    ordered_names: list[str] = []

    while remaining:
        ready = sorted(
            table_name
            for table_name in remaining
            if not (_table_dependencies(table_map[table_name], table_names) & remaining)
        )
        if not ready:
            # Preserve all tables and make cycles visible through detect_dependency_cycles().
            ready = sorted(remaining)
        for table_name in ready:
            ordered_names.append(table_name)
            remaining.remove(table_name)

    return [table_map[table_name] for table_name in ordered_names]


def _normalize_create_header(sql: str, table_name: str) -> str:
    return re.sub(
        rf"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?{re.escape(table_name)}\b",
        f"CREATE TABLE IF NOT EXISTS {table_name}",
        sql,
        count=1,
        flags=re.IGNORECASE,
    )


def _apply_type_mappings(sql: str) -> str:
    mapped = re.sub(
        r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
        TYPE_MAPPINGS["INTEGER PRIMARY KEY AUTOINCREMENT"],
        sql,
        flags=re.IGNORECASE,
    )
    mapped = re.sub(
        r"\bINTEGER\s+PRIMARY\s+KEY\b",
        TYPE_MAPPINGS["INTEGER PRIMARY KEY"],
        mapped,
        flags=re.IGNORECASE,
    )
    mapped = re.sub(r"\bDATETIME\b(?=\s*(?:DEFAULT|NOT|,|\)|$))", "TIMESTAMPTZ", mapped, flags=re.IGNORECASE)
    mapped = re.sub(r"\bTIMESTAMP\b(?=\s*(?:DEFAULT|NOT|,|\)|$))", "TIMESTAMPTZ", mapped, flags=re.IGNORECASE)
    mapped = re.sub(r"\bREAL\b", TYPE_MAPPINGS["REAL"], mapped, flags=re.IGNORECASE)
    return mapped


def generate_create_table_sql(table: TableInventory) -> str:
    sql = _normalize_create_header(table.sqlite_sql, table.name)
    sql = _apply_type_mappings(sql)
    normalized = "\n".join(line.rstrip() for line in sql.strip().splitlines())
    return normalized.rstrip(";") + ";"


def generate_index_sql(table: TableInventory) -> list[str]:
    statements: list[str] = []
    for index in table.indexes:
        if index.definition:
            definition = index.definition.strip().rstrip(";")
            definition = re.sub(r"\bCREATE\s+INDEX\b", "CREATE INDEX IF NOT EXISTS", definition, count=1, flags=re.IGNORECASE)
            definition = re.sub(
                r"\bCREATE\s+UNIQUE\s+INDEX\b",
                "CREATE UNIQUE INDEX IF NOT EXISTS",
                definition,
                count=1,
                flags=re.IGNORECASE,
            )
            statements.append(definition + ";")
        else:
            statements.append(f"-- INDEX {index.name} ON {table.name} captured from inventory; definition requires manual review.")
    return statements


def _find_boolean_candidates(table: TableInventory) -> list[str]:
    candidates: list[str] = []
    for column_name in BOOLEAN_CANDIDATE_COLUMNS:
        if re.search(rf"\b{re.escape(column_name)}\s+INTEGER\s+DEFAULT\s+[01]\b", table.sqlite_sql, flags=re.IGNORECASE):
            candidates.append(f"{table.name}.{column_name}")
    return sorted(candidates)


def _find_unsupported_constructs(tables: list[TableInventory]) -> list[str]:
    findings = set()
    for table in tables:
        for pattern in UNSUPPORTED_SOURCE_PATTERNS:
            if pattern in table.sqlite_sql:
                findings.add(f"{table.name}: {pattern}")
    return sorted(findings)


def _build_manual_review_items(tables: list[TableInventory], dependency_cycles: list[list[str]] | None = None) -> list[str]:
    items: list[str] = []
    for table in tables:
        for candidate in _find_boolean_candidates(table):
            items.append(f"Boolean candidate: {candidate}")
        if table.indexes and any(not index.definition for index in table.indexes):
            items.append(f"Index definitions require review: {table.name}")
        if re.search(r"\bTEXT\b.*\b(date|_date|created_at|updated_at|timestamp)\b", table.sqlite_sql, flags=re.IGNORECASE):
            items.append(f"Date/timestamp type review: {table.name}")
    for cycle in dependency_cycles or []:
        items.append("Dependency cycle requires ALTER TABLE FK phase: " + " -> ".join(cycle))
    return sorted(set(items))


def render_schema_sql(tables: list[TableInventory]) -> str:
    sections = [
        "-- Generated PostgreSQL schema draft.",
        "-- Offline artifact only: do not execute without Phase 5B schema deployment approval.",
        "BEGIN;",
        "",
    ]
    for table in tables:
        sections.append(f"-- Table: {table.name}")
        sections.append(generate_create_table_sql(table))
        index_sql = generate_index_sql(table)
        if index_sql:
            sections.extend(index_sql)
        sections.append("")
    sections.append("COMMIT;")
    sections.append("")
    return "\n".join(sections)


def render_summary(tables: list[TableInventory], sql: str, dependency_cycles: list[list[str]]) -> str:
    index_count = sum(len(table.indexes) for table in tables)
    foreign_key_count = sum(len(table.foreign_keys) for table in tables)
    unsupported_constructs = _find_unsupported_constructs(tables)
    manual_review_items = _build_manual_review_items(tables, dependency_cycles)
    represented_tables = sorted(table.name for table in tables if f"CREATE TABLE IF NOT EXISTS {table.name}" in sql)
    missing_tables = sorted(set(table.name for table in tables) - set(represented_tables))

    lines = [
        "# Generated PostgreSQL Schema Summary",
        "",
        "Generated offline by `postgres_schema_generator.py`. No database connection or deployment was attempted.",
        "",
        "## Statistics",
        "",
        f"- Table count: {len(tables)}",
        f"- Tables represented in SQL: {len(represented_tables)}",
        f"- Index count captured: {index_count}",
        f"- FK count captured: {foreign_key_count}",
        f"- Unsupported constructs: {len(unsupported_constructs)}",
        f"- Manual review items: {len(manual_review_items)}",
        f"- Dependency cycles: {len(dependency_cycles)}",
        "",
        "## Validation",
        "",
        f"- Every SQLite table represented: {'YES' if not missing_tables else 'NO'}",
        f"- FK inventory captured: {'YES' if foreign_key_count else 'NO'}",
        f"- Index inventory captured: {'YES' if index_count else 'NO'}",
        f"- Dependency ordering applied: {'YES' if not dependency_cycles else 'PARTIAL - cycles require ALTER TABLE phase'}",
        "- Deployment attempted: NO",
        "",
        "## Dependency Ordering",
        "",
        "- Table CREATE statements are ordered so referenced parent tables are emitted before child tables when no FK cycle exists.",
        "- Future executable index statements should be emitted after all table creation statements.",
        "- Future cyclic foreign keys should be emitted in a post-table `ALTER TABLE ... ADD CONSTRAINT` phase.",
        "",
        "## Dependency Cycles",
        "",
    ]
    if dependency_cycles:
        lines.extend(f"- {' -> '.join(cycle)}" for cycle in dependency_cycles)
    else:
        lines.append("- None detected.")
    lines.extend([
        "",
        "## Unsupported Constructs",
        "",
    ])
    lines.extend(f"- {item}" for item in unsupported_constructs[:100])
    if not unsupported_constructs:
        lines.append("- None after type mapping pass.")
    lines.extend(["", "## Manual Review Items", ""])
    lines.extend(f"- {item}" for item in manual_review_items[:150])
    if not manual_review_items:
        lines.append("- None.")
    if missing_tables:
        lines.extend(["", "## Missing Tables", ""])
        lines.extend(f"- {table_name}" for table_name in missing_tables)
    lines.append("")
    return "\n".join(lines)


def build_schema_plan(tables: list[TableInventory]) -> GeneratedSchemaPlan:
    dependency_cycles = detect_dependency_cycles(tables)
    ordered_tables = order_tables_by_dependencies(tables)
    sql = render_schema_sql(ordered_tables)
    summary = render_summary(ordered_tables, sql, dependency_cycles)
    return GeneratedSchemaPlan(
        sql=sql,
        summary=summary,
        table_count=len(ordered_tables),
        index_count=sum(len(table.indexes) for table in ordered_tables),
        foreign_key_count=sum(len(table.foreign_keys) for table in ordered_tables),
        unsupported_constructs=_find_unsupported_constructs(ordered_tables),
        manual_review_items=_build_manual_review_items(ordered_tables, dependency_cycles),
        dependency_cycles=dependency_cycles,
        ordered_tables=[table.name for table in ordered_tables],
    )


def generate_postgres_schema_plan(
    inventory_report_path: Path = DEFAULT_INVENTORY_REPORT,
    sql_output_path: Path = DEFAULT_SQL_OUTPUT,
    summary_output_path: Path = DEFAULT_SUMMARY_OUTPUT,
) -> GeneratedSchemaPlan:
    report_text = inventory_report_path.read_text(encoding="utf-8")
    tables = parse_schema_compatibility_report(report_text)
    plan = build_schema_plan(tables)
    sql_output_path.parent.mkdir(parents=True, exist_ok=True)
    summary_output_path.parent.mkdir(parents=True, exist_ok=True)
    sql_output_path.write_text(plan.sql, encoding="utf-8")
    summary_output_path.write_text(plan.summary, encoding="utf-8")
    return plan


if __name__ == "__main__":
    generated = generate_postgres_schema_plan()
    print(
        "Generated PostgreSQL schema draft: "
        f"tables={generated.table_count} indexes={generated.index_count} "
        f"foreign_keys={generated.foreign_key_count}"
    )
