import tempfile
import unittest
from pathlib import Path
import re

from postgres_schema_generator import (
    ForeignKeyInventory,
    IndexInventory,
    TableInventory,
    build_schema_plan,
    detect_dependency_cycles,
    generate_create_table_sql,
    generate_index_sql,
    generate_postgres_schema_plan,
    order_tables_by_dependencies,
    parse_schema_compatibility_report,
)


class PostgresSchemaGeneratorTests(unittest.TestCase):
    def test_autoincrement_mapping(self):
        table = TableInventory(
            name="sample",
            sqlite_sql="""
            CREATE TABLE sample (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                amount REAL DEFAULT 0,
                name TEXT
            )
            """,
        )
        sql = generate_create_table_sql(table)
        self.assertIn("id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql)
        self.assertIn("amount NUMERIC(18,2) DEFAULT 0", sql)
        self.assertIn("name TEXT", sql)

    def test_create_table_generation_preserves_fk(self):
        table = TableInventory(
            name="child",
            sqlite_sql="""
            CREATE TABLE child (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                parent_id INTEGER NOT NULL,
                FOREIGN KEY (parent_id) REFERENCES parent(id) ON DELETE CASCADE
            )
            """,
            foreign_keys=[ForeignKeyInventory("parent_id", "parent", "id", "CASCADE")],
        )
        plan = build_schema_plan([table])
        self.assertIn("CREATE TABLE IF NOT EXISTS child", plan.sql)
        self.assertIn("FOREIGN KEY (parent_id) REFERENCES parent(id) ON DELETE CASCADE", plan.sql)
        self.assertEqual(plan.foreign_key_count, 1)

    def test_timestamp_column_name_is_not_rewritten_as_type(self):
        table = TableInventory(
            name="audit_logs",
            sqlite_sql="CREATE TABLE audit_logs (timestamp DATETIME DEFAULT CURRENT_TIMESTAMP, created_at TIMESTAMP)",
        )
        sql = generate_create_table_sql(table)
        self.assertIn("timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP", sql)
        self.assertIn("created_at TIMESTAMPTZ", sql)
        self.assertNotIn("TIMESTAMPTZ TIMESTAMPTZ", sql)

    def test_index_generation_from_definition(self):
        table = TableInventory(
            name="sample",
            sqlite_sql="CREATE TABLE sample (id INTEGER PRIMARY KEY)",
            indexes=[
                IndexInventory(
                    name="idx_sample_name",
                    definition="CREATE INDEX idx_sample_name ON sample(name)",
                )
            ],
        )
        indexes = generate_index_sql(table)
        self.assertEqual(indexes[0], "CREATE INDEX IF NOT EXISTS idx_sample_name ON sample(name);")

    def test_summary_generation_counts_constructs(self):
        table = TableInventory(
            name="sample",
            sqlite_sql="""
            CREATE TABLE sample (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                is_active INTEGER DEFAULT 1
            )
            """,
            indexes=[IndexInventory("idx_sample_active")],
        )
        plan = build_schema_plan([table])
        self.assertEqual(plan.table_count, 1)
        self.assertEqual(plan.index_count, 1)
        self.assertTrue(any("AUTOINCREMENT" in item for item in plan.unsupported_constructs))
        self.assertTrue(any("Boolean candidate" in item for item in plan.manual_review_items))
        self.assertIn("Every SQLite table represented: YES", plan.summary)

    def test_parse_report_and_generate_files_without_db_access(self):
        report = """
## Per-Table Detail
### `parent`

```sql
CREATE TABLE parent (id INTEGER PRIMARY KEY, name TEXT)
```

### `child`

**Foreign keys:**
- `parent_id` \u2192 `parent.id` (on_delete=CASCADE)

**Indexes:** `idx_child_parent`

```sql
CREATE TABLE child (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    parent_id INTEGER,
    FOREIGN KEY (parent_id) REFERENCES parent(id) ON DELETE CASCADE
)
```
"""
        parsed = parse_schema_compatibility_report(report)
        self.assertEqual([table.name for table in parsed], ["child", "parent"])
        self.assertEqual(len(parsed[0].foreign_keys), 1)
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir)
            report_path = temp_path / "inventory.md"
            sql_path = temp_path / "schema.sql"
            summary_path = temp_path / "summary.md"
            report_path.write_text(report, encoding="utf-8")
            plan = generate_postgres_schema_plan(report_path, sql_path, summary_path)
            self.assertEqual(plan.table_count, 2)
            self.assertEqual(plan.ordered_tables, ["parent", "child"])
            self.assertTrue(sql_path.exists())
            self.assertTrue(summary_path.exists())
            generated_sql = sql_path.read_text(encoding="utf-8")
            self.assertLess(generated_sql.index("CREATE TABLE IF NOT EXISTS parent"), generated_sql.index("CREATE TABLE IF NOT EXISTS child"))
            self.assertIn("Deployment attempted: NO", summary_path.read_text(encoding="utf-8"))

    def test_companies_ordered_before_audit_logs(self):
        companies = TableInventory(name="companies", sqlite_sql="CREATE TABLE companies (key TEXT PRIMARY KEY)")
        audit_logs = TableInventory(
            name="audit_logs",
            sqlite_sql="""
            CREATE TABLE audit_logs (
                id INTEGER PRIMARY KEY,
                company_key TEXT,
                FOREIGN KEY (company_key) REFERENCES companies(key)
            )
            """,
            foreign_keys=[ForeignKeyInventory("company_key", "companies", "key", "NO ACTION")],
        )
        plan = build_schema_plan([audit_logs, companies])
        self.assertEqual(plan.ordered_tables, ["companies", "audit_logs"])
        self.assertLess(plan.sql.index("CREATE TABLE IF NOT EXISTS companies"), plan.sql.index("CREATE TABLE IF NOT EXISTS audit_logs"))

    def test_parent_tables_ordered_before_child_tables(self):
        grandparent = TableInventory(name="grandparent", sqlite_sql="CREATE TABLE grandparent (id INTEGER PRIMARY KEY)")
        parent = TableInventory(
            name="parent",
            sqlite_sql="CREATE TABLE parent (id INTEGER PRIMARY KEY, grandparent_id INTEGER, FOREIGN KEY (grandparent_id) REFERENCES grandparent(id))",
            foreign_keys=[ForeignKeyInventory("grandparent_id", "grandparent", "id", "NO ACTION")],
        )
        child = TableInventory(
            name="child",
            sqlite_sql="CREATE TABLE child (id INTEGER PRIMARY KEY, parent_id INTEGER, FOREIGN KEY (parent_id) REFERENCES parent(id))",
            foreign_keys=[ForeignKeyInventory("parent_id", "parent", "id", "NO ACTION")],
        )
        ordered = order_tables_by_dependencies([child, parent, grandparent])
        self.assertEqual([table.name for table in ordered], ["grandparent", "parent", "child"])

    def test_cycle_detection_reports_cycle(self):
        table_a = TableInventory(
            name="table_a",
            sqlite_sql="CREATE TABLE table_a (id INTEGER PRIMARY KEY, b_id INTEGER, FOREIGN KEY (b_id) REFERENCES table_b(id))",
            foreign_keys=[ForeignKeyInventory("b_id", "table_b", "id", "NO ACTION")],
        )
        table_b = TableInventory(
            name="table_b",
            sqlite_sql="CREATE TABLE table_b (id INTEGER PRIMARY KEY, a_id INTEGER, FOREIGN KEY (a_id) REFERENCES table_a(id))",
            foreign_keys=[ForeignKeyInventory("a_id", "table_a", "id", "NO ACTION")],
        )
        cycles = detect_dependency_cycles([table_a, table_b])
        self.assertEqual(len(cycles), 1)
        self.assertEqual(set(cycles[0]), {"table_a", "table_b"})
        plan = build_schema_plan([table_a, table_b])
        self.assertEqual(len(plan.dependency_cycles), 1)
        self.assertIn("Dependency cycles: 1", plan.summary)
        self.assertIn("ALTER TABLE FK phase", plan.summary)

    def test_generated_schema_has_51_tables_and_no_sqlite_forbidden_syntax(self):
        plan = generate_postgres_schema_plan()
        self.assertEqual(plan.table_count, 51)
        self.assertEqual(plan.foreign_key_count, 47)
        self.assertEqual(len(plan.dependency_cycles), 0)
        created_tables = re.findall(r"\bCREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+([A-Za-z_][A-Za-z0-9_]*)\b", plan.sql)
        self.assertEqual(len(created_tables), 51)
        for forbidden in ("AUTOINCREMENT", "PRAGMA", "sqlite_master", "INSERT OR IGNORE", "BEGIN IMMEDIATE"):
            self.assertNotIn(forbidden, plan.sql)


if __name__ == "__main__":
    unittest.main()
