-- Generated PostgreSQL schema draft.
-- Offline artifact only: do not execute without Phase 5B schema deployment approval.
BEGIN;

-- Table: accounting_periods
CREATE TABLE IF NOT EXISTS accounting_periods (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            period_label TEXT NOT NULL,
            start_date TEXT NOT NULL,
            end_date TEXT NOT NULL,
            is_locked INTEGER DEFAULT 0,
            locked_at TIMESTAMPTZ,
            locked_by TEXT, status TEXT DEFAULT 'Open', closed_at TIMESTAMPTZ, closed_by TEXT, reopened_at TIMESTAMPTZ, reopened_by TEXT,
            UNIQUE(company_key, period_label)
        );
-- INDEX idx_accounting_periods_company_status ON accounting_periods captured from inventory; definition requires manual review.

-- Table: accounts_payable
CREATE TABLE IF NOT EXISTS accounts_payable (id BIGINT PRIMARY KEY, vendor TEXT, amount NUMERIC(18,2), status TEXT, due_date TEXT);

-- Table: branch_type_catalog
CREATE TABLE IF NOT EXISTS branch_type_catalog (
            branch_type_key TEXT PRIMARY KEY,
            branch_type_name TEXT NOT NULL,
            description TEXT,
            is_active INTEGER DEFAULT 1,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        );

-- Table: companies
CREATE TABLE IF NOT EXISTS companies
                     (key TEXT PRIMARY KEY,
                      name TEXT,
                      tin TEXT,
                      sub_admin_key TEXT,
                      staff_key TEXT,
                      recovery_answer TEXT,
                      admin_email TEXT,
                      status TEXT DEFAULT 'Active',
                      subscription_end_date TIMESTAMPTZ,
                      deployment_status TEXT DEFAULT 'Live',
                      expiry_date TIMESTAMPTZ,
                      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, contact_email TEXT, barcode_input_source TEXT DEFAULT 'Keyboard Entry', number_of_branches INTEGER DEFAULT 1, max_branches INTEGER DEFAULT 1, branch_price_per_month NUMERIC(18,2) DEFAULT 0.0, subscription_expiry TEXT, phone_number TEXT, physical_address TEXT, industry TEXT, currency TEXT DEFAULT 'GHS', logo_url TEXT);

-- Table: customers
CREATE TABLE IF NOT EXISTS customers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            name TEXT NOT NULL,
            email TEXT,
            phone TEXT,
            address TEXT,
            currency TEXT DEFAULT 'GHS',
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, customer_id TEXT, current_balance NUMERIC(18,2) DEFAULT 0,
            UNIQUE(company_key, name)
        );
-- INDEX idx_customers_company_name ON customers captured from inventory; definition requires manual review.
-- INDEX idx_customers_company_customer_id ON customers captured from inventory; definition requires manual review.

-- Table: database_identity
CREATE TABLE IF NOT EXISTS database_identity (
            instance_id TEXT PRIMARY KEY,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            last_verified_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        , schema_version INTEGER DEFAULT 0, last_startup_at TIMESTAMPTZ, backend_label TEXT DEFAULT 'SQLite', environment_label TEXT);

-- Table: journal_entries
CREATE TABLE IF NOT EXISTS journal_entries (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT,
            date TEXT NOT NULL,
            description TEXT NOT NULL,
            reference TEXT,
            created_by TEXT,
            branch_id TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        , customer_id INTEGER, supplier_id INTEGER, inventory_item_id INTEGER, payment_id INTEGER, source_module TEXT, source_table TEXT, source_id INTEGER, source_type TEXT, reversed_entry_id INTEGER, is_voided INTEGER DEFAULT 0, voided_at TIMESTAMPTZ, voided_by TEXT, approval_status TEXT DEFAULT 'Posted', document_number TEXT, document_type TEXT, posted_at TIMESTAMPTZ, posted_by TEXT, source_document_type TEXT, source_document_id INTEGER);
-- INDEX idx_journal_entries_supplier ON journal_entries captured from inventory; definition requires manual review.
-- INDEX idx_journal_entries_customer ON journal_entries captured from inventory; definition requires manual review.
-- INDEX idx_journal_entries_source ON journal_entries captured from inventory; definition requires manual review.
-- INDEX idx_journal_entries_reporting ON journal_entries captured from inventory; definition requires manual review.
-- INDEX idx_journal_entries_company_date ON journal_entries captured from inventory; definition requires manual review.

-- Table: license_payment_transactions
CREATE TABLE IF NOT EXISTS license_payment_transactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference TEXT UNIQUE,
            company_key TEXT,
            company_name TEXT,
            payer_email TEXT,
            payment_context TEXT DEFAULT 'license_activation',
            expected_amount INTEGER DEFAULT 0,
            currency TEXT DEFAULT 'GHS',
            status TEXT DEFAULT 'initialized',
            authorization_url TEXT,
            callback_url TEXT,
            metadata_json TEXT,
            gateway_status_summary TEXT,
            paid_at TIMESTAMPTZ,
            verified_at TIMESTAMPTZ,
            activated_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        , plan_name TEXT, configured_amount NUMERIC(18,2) DEFAULT 0, configured_duration_months INTEGER DEFAULT 0, configured_duration_days INTEGER DEFAULT 0);
-- INDEX idx_license_payment_transactions_plan_status ON license_payment_transactions captured from inventory; definition requires manual review.
-- INDEX idx_license_payment_transactions_verified_at ON license_payment_transactions captured from inventory; definition requires manual review.
-- INDEX idx_license_payment_transactions_company_status ON license_payment_transactions captured from inventory; definition requires manual review.

-- Table: maintenance_settings
CREATE TABLE IF NOT EXISTS maintenance_settings
                     (id BIGINT PRIMARY KEY,
                      maintenance_date TEXT,
                      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, start_time TEXT, end_time TEXT, is_active INTEGER DEFAULT 0, message TEXT);

-- Table: migration_history
CREATE TABLE IF NOT EXISTS migration_history (
            migration_id TEXT PRIMARY KEY,
            description TEXT,
            applied_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        );

-- Table: migration_logs
CREATE TABLE IF NOT EXISTS migration_logs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            version INTEGER,
            description TEXT,
            status TEXT NOT NULL,
            backup_path TEXT,
            company_count_before INTEGER DEFAULT 0,
            company_count_after INTEGER DEFAULT 0,
            row_counts_before TEXT,
            row_counts_after TEXT,
            details TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        );

-- Table: payments
CREATE TABLE IF NOT EXISTS payments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            payment_date TEXT NOT NULL,
            payment_type TEXT NOT NULL,
            customer_id INTEGER,
            supplier_id INTEGER,
            invoice_id INTEGER,
            bill_id INTEGER,
            amount NUMERIC(18,2) DEFAULT 0,
            currency TEXT DEFAULT 'GHS',
            method TEXT,
            reference TEXT,
            created_by TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        , bank_account_id INTEGER, approval_status TEXT DEFAULT 'Draft', posted_entry_id INTEGER, void_entry_id INTEGER, last_journal_sync_at TIMESTAMPTZ, status TEXT DEFAULT 'Draft', submitted_at TIMESTAMPTZ, approved_at TIMESTAMPTZ, approved_by TEXT, cancelled_at TIMESTAMPTZ, cancelled_by TEXT);
-- INDEX idx_payments_company_status ON payments captured from inventory; definition requires manual review.

-- Table: payroll_records
CREATE TABLE IF NOT EXISTS payroll_records (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            payroll_id INTEGER,
            period_start TEXT,
            period_end TEXT,
            employee_name TEXT NOT NULL,
            gross_pay NUMERIC(18,2) DEFAULT 0,
            deductions NUMERIC(18,2) DEFAULT 0,
            net_pay NUMERIC(18,2) DEFAULT 0,
            status TEXT DEFAULT 'Draft',
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        );

-- Table: schema_version
CREATE TABLE IF NOT EXISTS schema_version (
            version BIGINT PRIMARY KEY,
            description TEXT NOT NULL,
            applied_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        );

-- Table: subscription_plan_settings
CREATE TABLE IF NOT EXISTS subscription_plan_settings (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            plan_name TEXT UNIQUE,
            configured_amount NUMERIC(18,2),
            currency TEXT DEFAULT 'GHS',
            duration_months INTEGER DEFAULT 0,
            duration_days INTEGER DEFAULT 0,
            features_json TEXT,
            updated_by TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        );
-- INDEX idx_subscription_plan_settings_plan_name ON subscription_plan_settings captured from inventory; definition requires manual review.

-- Table: suppliers
CREATE TABLE IF NOT EXISTS suppliers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            name TEXT NOT NULL,
            email TEXT,
            phone TEXT,
            address TEXT,
            currency TEXT DEFAULT 'GHS',
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, category TEXT,
            UNIQUE(company_key, name)
        );

-- Table: system_logs
CREATE TABLE IF NOT EXISTS system_logs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            timestamp TEXT,
            level TEXT,
            module_name TEXT,
            message TEXT
        );

-- Table: system_settings
CREATE TABLE IF NOT EXISTS system_settings (
                id BIGINT PRIMARY KEY,
                master_price_per_month NUMERIC(18,2) DEFAULT 500,
                updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            , base_currency TEXT DEFAULT 'GHS', display_currency TEXT DEFAULT 'GHS', exchange_rate NUMERIC(18,2) DEFAULT 1.0, journal_source_of_truth INTEGER DEFAULT 1, legacy_mirror_mode TEXT DEFAULT 'mirror', enforce_document_approval INTEGER DEFAULT 0, inventory_cost_method TEXT DEFAULT 'weighted_average', bank_reconciliation_mode TEXT DEFAULT 'journal_plus_payment');

-- Table: transactions
CREATE TABLE IF NOT EXISTS transactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            transaction_date TEXT NOT NULL,
            account TEXT NOT NULL,
            description TEXT,
            debit NUMERIC(18,2) DEFAULT 0,
            credit NUMERIC(18,2) DEFAULT 0,
            reference TEXT,
            created_by TEXT,
            branch_id TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        );

-- Table: audit_logs
CREATE TABLE IF NOT EXISTS audit_logs
                     (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                      company_key TEXT,
                      user_role TEXT,
                      action TEXT,
                      module_name TEXT, details TEXT, ip_address TEXT, branch_id TEXT, action_type TEXT, document_ref TEXT, before_after_summary TEXT, event_id TEXT,
                      FOREIGN KEY (company_key) REFERENCES companies(key));
-- INDEX idx_audit_logs_action_type ON audit_logs captured from inventory; definition requires manual review.
-- INDEX idx_audit_logs_company_timestamp ON audit_logs captured from inventory; definition requires manual review.

-- Table: bills
CREATE TABLE IF NOT EXISTS bills (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            supplier_id INTEGER,
            bill_number TEXT,
            bill_date TEXT NOT NULL,
            due_date TEXT,
            status TEXT DEFAULT 'Draft',
            amount NUMERIC(18,2) DEFAULT 0,
            currency TEXT DEFAULT 'GHS',
            description TEXT,
            created_by TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, input_vat NUMERIC(18,2) DEFAULT 0, output_vat NUMERIC(18,2) DEFAULT 0, approval_status TEXT DEFAULT 'Draft', posted_entry_id INTEGER, void_entry_id INTEGER, last_journal_sync_at TIMESTAMPTZ, submitted_at TIMESTAMPTZ, approved_at TIMESTAMPTZ, approved_by TEXT, cancelled_at TIMESTAMPTZ, cancelled_by TEXT, purchase_classification TEXT DEFAULT 'Inventory Purchase', payment_method TEXT, expense_account_name TEXT, asset_name TEXT, asset_category TEXT,
            FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
        );
-- INDEX idx_bills_company_status ON bills captured from inventory; definition requires manual review.
-- INDEX idx_bills_company_bill_number ON bills captured from inventory; definition requires manual review.

-- Table: branch_type_module_defaults
CREATE TABLE IF NOT EXISTS branch_type_module_defaults (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            branch_type_key TEXT NOT NULL,
            module_key TEXT NOT NULL,
            is_enabled INTEGER DEFAULT 1,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(branch_type_key, module_key),
            FOREIGN KEY (branch_type_key) REFERENCES branch_type_catalog (branch_type_key)
        );
-- INDEX idx_branch_type_module_defaults_type ON branch_type_module_defaults captured from inventory; definition requires manual review.

-- Table: branches
CREATE TABLE IF NOT EXISTS branches (
                branch_id TEXT PRIMARY KEY,
                company_key TEXT NOT NULL,
                branch_name TEXT NOT NULL,
                location TEXT,
                branch_type TEXT,
                branch_access_key TEXT UNIQUE,
                contact_number TEXT,
                branch_manager TEXT,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, is_active INTEGER DEFAULT 1, manager_user_id TEXT, deployment_status TEXT DEFAULT 'active', branch_tier TEXT DEFAULT 'standard', branch_code TEXT,
                FOREIGN KEY (company_key) REFERENCES companies (key) ON DELETE CASCADE
            );
-- INDEX idx_branches_access_key ON branches captured from inventory; definition requires manual review.
-- INDEX idx_branches_company ON branches captured from inventory; definition requires manual review.

-- Table: cashier_closings
CREATE TABLE IF NOT EXISTS cashier_closings (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            branch_id TEXT DEFAULT '',
            cashier TEXT NOT NULL,
            closing_date TEXT NOT NULL,
            expected_cash NUMERIC(18,2) DEFAULT 0,
            counted_cash NUMERIC(18,2) DEFAULT 0,
            difference NUMERIC(18,2) DEFAULT 0,
            notes TEXT,
            closed_by TEXT,
            closed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (company_key) REFERENCES companies (key) ON DELETE CASCADE
        );
-- INDEX idx_cashier_closings_company_date ON cashier_closings captured from inventory; definition requires manual review.
-- INDEX idx_cashier_closings_unique_drawer ON cashier_closings captured from inventory; definition requires manual review.

-- Table: chart_of_accounts
CREATE TABLE IF NOT EXISTS chart_of_accounts
                     (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      company_key TEXT,
                      account_code TEXT,
                      account_name TEXT,
                      account_type TEXT,
                      balance NUMERIC(18,2) DEFAULT 0.0,
                      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, name TEXT, type TEXT, parent_id INTEGER, category TEXT, code TEXT, posting_allowed INTEGER DEFAULT 1, control_account INTEGER DEFAULT 0, allow_manual_posting INTEGER DEFAULT 1, is_active INTEGER DEFAULT 1,
                      FOREIGN KEY (company_key) REFERENCES companies(key));
-- INDEX idx_chart_of_accounts_account_code_unique ON chart_of_accounts captured from inventory; definition requires manual review.
-- INDEX idx_chart_of_accounts_control_account ON chart_of_accounts captured from inventory; definition requires manual review.
-- INDEX idx_chart_of_accounts_active ON chart_of_accounts captured from inventory; definition requires manual review.
-- INDEX idx_chart_of_accounts_parent_id ON chart_of_accounts captured from inventory; definition requires manual review.
-- INDEX idx_chart_of_accounts_type ON chart_of_accounts captured from inventory; definition requires manual review.

-- Table: company_subscriptions
CREATE TABLE IF NOT EXISTS company_subscriptions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT UNIQUE,
            plan_name TEXT,
            status TEXT DEFAULT 'trial',
            start_date TEXT,
            end_date TEXT,
            last_payment_reference TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (company_key) REFERENCES companies (key)
        );
-- INDEX idx_company_subscriptions_status_end_date ON company_subscriptions captured from inventory; definition requires manual review.
-- INDEX idx_company_subscriptions_company_key ON company_subscriptions captured from inventory; definition requires manual review.

-- Table: counterparties
CREATE TABLE IF NOT EXISTS counterparties (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_key TEXT NOT NULL,
                party_name TEXT NOT NULL,
                party_type TEXT NOT NULL,
                city_region TEXT,
                last_transaction TEXT,
                balance NUMERIC(18,2) DEFAULT 0,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(company_key, party_name, party_type),
                FOREIGN KEY (company_key) REFERENCES companies (key) ON DELETE CASCADE
            );
-- INDEX idx_counterparties_company_type ON counterparties captured from inventory; definition requires manual review.

-- Table: fixed_assets
CREATE TABLE IF NOT EXISTS fixed_assets
                     (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      company_key TEXT,
                      asset_name TEXT,
                      purchase_cost NUMERIC(18,2),
                      dep_rate NUMERIC(18,2),
                      accum_dep NUMERIC(18,2) DEFAULT 0.0,
                      book_value NUMERIC(18,2),
                      purchase_date TEXT,
                      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, asset_category TEXT, cost NUMERIC(18,2) DEFAULT 0, depreciation_rate NUMERIC(18,2) DEFAULT 0, accumulated_depreciation NUMERIC(18,2) DEFAULT 0, location TEXT, status TEXT DEFAULT 'Active', opening_book_value NUMERIC(18,2) DEFAULT 0, useful_life_years NUMERIC(18,2) DEFAULT 0, residual_value NUMERIC(18,2) DEFAULT 0, depreciation_method TEXT DEFAULT 'Straight-line', last_depreciation_date TEXT, supplier_id INTEGER, custodian TEXT, description TEXT, notes TEXT, acquisition_type TEXT DEFAULT 'Opening Balance Asset', acquisition_source TEXT, payment_method TEXT, owner_contributor_name TEXT, owner_name TEXT, approval_status TEXT DEFAULT 'Posted', approved_at TIMESTAMPTZ, approved_by TEXT, posted_entry_id INTEGER, acquisition_journal_entry_id INTEGER, last_journal_sync_at TIMESTAMPTZ, created_by TEXT,
                      FOREIGN KEY (company_key) REFERENCES companies(key));

-- Table: inventory
CREATE TABLE IF NOT EXISTS inventory
                     (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      company_key TEXT,
                      item_name TEXT,
                      unit TEXT,
                      qty NUMERIC(18,2) DEFAULT 0.0,
                      price NUMERIC(18,2) DEFAULT 0.0,
                      cost_price NUMERIC(18,2) DEFAULT 0.0,
                      warehouse TEXT DEFAULT 'Main',
                      barcode TEXT,
                      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, item_code TEXT, category TEXT, description TEXT, min_stock_level NUMERIC(18,2) DEFAULT 10, tax_rate NUMERIC(18,2) DEFAULT 0, warehouse_location TEXT, is_active INTEGER DEFAULT 1, opening_balance NUMERIC(18,2) DEFAULT 0, inventory_account_id INTEGER, cogs_account_id INTEGER, brand TEXT, supplier_name TEXT, expiry_date TEXT, batch_number TEXT, vat_category TEXT,
                      FOREIGN KEY (company_key) REFERENCES companies(key));
-- INDEX idx_inv_barcode ON inventory captured from inventory; definition requires manual review.
-- INDEX idx_inv_name ON inventory captured from inventory; definition requires manual review.
-- INDEX idx_inv_comp ON inventory captured from inventory; definition requires manual review.

-- Table: inventory_import_batches
CREATE TABLE IF NOT EXISTS inventory_import_batches (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            import_reference TEXT UNIQUE,
            company_key TEXT NOT NULL,
            branch_id TEXT,
            imported_item_count INTEGER DEFAULT 0,
            created_count INTEGER DEFAULT 0,
            updated_count INTEGER DEFAULT 0,
            skipped_count INTEGER DEFAULT 0,
            error_count INTEGER DEFAULT 0,
            total_opening_value NUMERIC(18,2) DEFAULT 0,
            imported_by TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            opening_posted INTEGER DEFAULT 0,
            opening_posted_entry_id INTEGER,
            opening_posted_at TIMESTAMPTZ,
            opening_posted_by TEXT,
            FOREIGN KEY (company_key) REFERENCES companies (key) ON DELETE CASCADE
        );
-- INDEX idx_inventory_import_batches_company ON inventory_import_batches captured from inventory; definition requires manual review.
-- INDEX idx_inventory_import_batches_reference ON inventory_import_batches captured from inventory; definition requires manual review.

-- Table: invoices
CREATE TABLE IF NOT EXISTS invoices (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            customer_id INTEGER,
            invoice_number TEXT,
            invoice_date TEXT NOT NULL,
            due_date TEXT,
            status TEXT DEFAULT 'Draft',
            amount NUMERIC(18,2) DEFAULT 0,
            currency TEXT DEFAULT 'GHS',
            description TEXT,
            created_by TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, input_vat NUMERIC(18,2) DEFAULT 0, output_vat NUMERIC(18,2) DEFAULT 0, approval_status TEXT DEFAULT 'Draft', posted_entry_id INTEGER, void_entry_id INTEGER, last_journal_sync_at TIMESTAMPTZ, submitted_at TIMESTAMPTZ, approved_at TIMESTAMPTZ, approved_by TEXT, cancelled_at TIMESTAMPTZ, cancelled_by TEXT,
            FOREIGN KEY (customer_id) REFERENCES customers(id)
        );
-- INDEX idx_invoices_company_status ON invoices captured from inventory; definition requires manual review.
-- INDEX idx_invoices_company_invoice_number ON invoices captured from inventory; definition requires manual review.

-- Table: payroll
CREATE TABLE IF NOT EXISTS payroll
                     (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      company_key TEXT,
                      emp_name TEXT,
                      basic_salary NUMERIC(18,2),
                      ssnit_t1 NUMERIC(18,2),
                      ssnit_t2 NUMERIC(18,2),
                      ssnit_t3 NUMERIC(18,2) DEFAULT 0.0,
                      taxable_income NUMERIC(18,2),
                      paye NUMERIC(18,2),
                      net_salary NUMERIC(18,2),
                      month TEXT,
                      year TEXT,
                      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, emp_id TEXT, bank_name TEXT, account_number TEXT, allowances NUMERIC(18,2) DEFAULT 0, payment_status TEXT DEFAULT 'Unpaid', deductions NUMERIC(18,2) DEFAULT 0, status TEXT DEFAULT 'Active', payment_method TEXT, approval_status TEXT DEFAULT 'Posted', approved_at TIMESTAMPTZ, approved_by TEXT, posted_entry_id INTEGER, last_journal_sync_at TIMESTAMPTZ, created_by TEXT,
                      FOREIGN KEY (company_key) REFERENCES companies(key));

-- Table: pending_approvals
CREATE TABLE IF NOT EXISTS pending_approvals (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_key TEXT,
                payment_reference TEXT UNIQUE,
                amount NUMERIC(18,2),
                payment_method TEXT,
                plan_requested TEXT,
                status TEXT DEFAULT 'Pending',
                admin_notes TEXT,
                timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (company_key) REFERENCES companies (key)
            );

-- Table: pos_returns
CREATE TABLE IF NOT EXISTS pos_returns (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            branch_id TEXT DEFAULT '',
            original_sale_reference TEXT NOT NULL,
            return_reference TEXT NOT NULL,
            pos_sale_line_id INTEGER,
            item_id INTEGER,
            item_name TEXT NOT NULL,
            qty_returned NUMERIC(18,2) DEFAULT 0,
            unit_price NUMERIC(18,2) DEFAULT 0,
            refund_amount NUMERIC(18,2) DEFAULT 0,
            reason TEXT,
            refund_method TEXT,
            returned_by TEXT,
            returned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            posted_entry_id INTEGER,
            status TEXT DEFAULT 'Posted',
            FOREIGN KEY (company_key) REFERENCES companies (key) ON DELETE CASCADE
        );
-- INDEX idx_pos_returns_sale_line ON pos_returns captured from inventory; definition requires manual review.
-- INDEX idx_pos_returns_reference_line ON pos_returns captured from inventory; definition requires manual review.

-- Table: pos_sales
CREATE TABLE IF NOT EXISTS pos_sales (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            branch_id TEXT DEFAULT '',
            sale_reference TEXT NOT NULL,
            receipt_number TEXT NOT NULL,
            sale_date TEXT NOT NULL,
            sale_datetime TEXT,
            cashier TEXT,
            payment_method TEXT,
            customer_id INTEGER,
            subtotal NUMERIC(18,2) DEFAULT 0,
            discount_total NUMERIC(18,2) DEFAULT 0,
            tax_total NUMERIC(18,2) DEFAULT 0,
            grand_total NUMERIC(18,2) DEFAULT 0,
            amount_tendered NUMERIC(18,2) DEFAULT 0,
            change_due NUMERIC(18,2) DEFAULT 0,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, posted_entry_id INTEGER, cogs_posted_entry_id INTEGER, last_journal_sync_at TIMESTAMPTZ,
            FOREIGN KEY (company_key) REFERENCES companies (key) ON DELETE CASCADE
        );
-- INDEX idx_pos_sales_cashier_date ON pos_sales captured from inventory; definition requires manual review.
-- INDEX idx_pos_sales_reference ON pos_sales captured from inventory; definition requires manual review.

-- Table: pos_suspended_sales
CREATE TABLE IF NOT EXISTS pos_suspended_sales (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            branch_id TEXT DEFAULT '',
            suspend_reference TEXT NOT NULL,
            cashier TEXT,
            cart_json TEXT NOT NULL,
            note TEXT,
            status TEXT DEFAULT 'suspended',
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            resumed_at TIMESTAMPTZ,
            cancelled_at TIMESTAMPTZ,
            FOREIGN KEY (company_key) REFERENCES companies (key) ON DELETE CASCADE
        );
-- INDEX idx_pos_suspended_sales_status ON pos_suspended_sales captured from inventory; definition requires manual review.
-- INDEX idx_pos_suspended_sales_reference ON pos_suspended_sales captured from inventory; definition requires manual review.

-- Table: purchase_orders
CREATE TABLE IF NOT EXISTS purchase_orders
                     (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      company_key TEXT,
                      po_no TEXT,
                      supplier_name TEXT,
                      order_date TEXT,
                      total_amount NUMERIC(18,2),
                      status TEXT DEFAULT 'Pending',
                      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, item TEXT, quantity INTEGER, cost NUMERIC(18,2),
                      FOREIGN KEY (company_key) REFERENCES companies(key));

-- Table: sales_invoices
CREATE TABLE IF NOT EXISTS sales_invoices
                     (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      company_key TEXT,
                      invoice_no TEXT,
                      customer_name TEXT,
                      customer_email TEXT,
                      invoice_date TEXT,
                      due_date TEXT,
                      total_amount NUMERIC(18,2),
                      status TEXT DEFAULT 'Pending',
                      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                      FOREIGN KEY (company_key) REFERENCES companies(key));

-- Table: supplier_transactions
CREATE TABLE IF NOT EXISTS supplier_transactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            supplier_id INTEGER NOT NULL,
            transaction_type TEXT NOT NULL,
            amount NUMERIC(18,2) NOT NULL,
            description TEXT,
            reference TEXT,
            transaction_date TEXT NOT NULL,
            created_by TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (company_key) REFERENCES companies(key) ON DELETE CASCADE,
            FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE
        );
-- INDEX idx_supplier_transactions_company_date ON supplier_transactions captured from inventory; definition requires manual review.
-- INDEX idx_supplier_transactions_supplier_date ON supplier_transactions captured from inventory; definition requires manual review.

-- Table: users
CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_key TEXT NOT NULL,
                full_name TEXT NOT NULL,
                login_key TEXT NOT NULL UNIQUE,
                role TEXT NOT NULL,
                status TEXT DEFAULT 'Active',
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, password_hash TEXT, branch_id TEXT, user_id TEXT, security_question TEXT, security_answer TEXT, current_session_id TEXT, last_login_device TEXT,
                FOREIGN KEY (company_key) REFERENCES companies (key) ON DELETE CASCADE
            );
-- INDEX idx_users_user_id_runtime ON users captured from inventory; definition requires manual review.
-- INDEX idx_users_user_id ON users captured from inventory; definition requires manual review.
-- INDEX idx_users_login_key ON users captured from inventory; definition requires manual review.

-- Table: vouchers
CREATE TABLE IF NOT EXISTS vouchers
                     (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      company_key TEXT,
                      date TEXT,
                      v_type TEXT,
                      ledger TEXT,
                      debit NUMERIC(18,2) DEFAULT 0.0,
                      credit NUMERIC(18,2) DEFAULT 0.0,
                      payment_method TEXT,
                      narration TEXT,
                      ref_no TEXT,
                      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, balance_after NUMERIC(18,2) DEFAULT 0, reference_no TEXT, is_cleared INTEGER DEFAULT 1, created_by TEXT, status TEXT DEFAULT 'Active', branch_id TEXT, approval_status TEXT DEFAULT 'Draft', is_voided INTEGER DEFAULT 0, voided_at TIMESTAMPTZ, voided_by TEXT, submitted_at TIMESTAMPTZ, approved_at TIMESTAMPTZ, approved_by TEXT, posted_entry_id INTEGER, last_journal_sync_at TIMESTAMPTZ,
                      FOREIGN KEY (company_key) REFERENCES companies(key));
-- INDEX idx_vouch_date ON vouchers captured from inventory; definition requires manual review.

-- Table: bank_accounts
CREATE TABLE IF NOT EXISTS bank_accounts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            branch_id TEXT,
            account_name TEXT NOT NULL,
            account_number TEXT,
            bank_name TEXT,
            account_type TEXT DEFAULT 'Bank',
            currency TEXT DEFAULT 'GHS',
            balance NUMERIC(18,2) DEFAULT 0,
            created_by TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (company_key) REFERENCES companies(key) ON DELETE CASCADE,
            FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE SET NULL
        );
-- INDEX idx_bank_accounts_company ON bank_accounts captured from inventory; definition requires manual review.

-- Table: bill_lines
CREATE TABLE IF NOT EXISTS bill_lines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            bill_id INTEGER NOT NULL,
            item_name TEXT NOT NULL,
            quantity NUMERIC(18,2) DEFAULT 1,
            unit_price NUMERIC(18,2) DEFAULT 0,
            line_total NUMERIC(18,2) DEFAULT 0,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (bill_id) REFERENCES bills(id) ON DELETE CASCADE
        );
-- INDEX idx_bill_lines_bill_id ON bill_lines captured from inventory; definition requires manual review.

-- Table: branch_module_grants
CREATE TABLE IF NOT EXISTS branch_module_grants (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            branch_id TEXT NOT NULL,
            module_key TEXT NOT NULL,
            is_enabled INTEGER DEFAULT 1,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(company_key, branch_id, module_key),
            FOREIGN KEY (company_key) REFERENCES companies (key) ON DELETE CASCADE,
            FOREIGN KEY (branch_id) REFERENCES branches (branch_id) ON DELETE CASCADE
        );
-- INDEX idx_branch_module_grants_company_branch ON branch_module_grants captured from inventory; definition requires manual review.

-- Table: customer_transactions
CREATE TABLE IF NOT EXISTS customer_transactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            customer_id INTEGER NOT NULL,
            branch_id TEXT,
            transaction_type TEXT NOT NULL,
            amount NUMERIC(18,2) NOT NULL,
            description TEXT,
            reference TEXT,
            transaction_date TEXT NOT NULL,
            created_by TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (company_key) REFERENCES companies(key) ON DELETE CASCADE,
            FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
            FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE SET NULL
        );
-- INDEX idx_customer_transactions_company_date ON customer_transactions captured from inventory; definition requires manual review.
-- INDEX idx_customer_transactions_customer_date ON customer_transactions captured from inventory; definition requires manual review.

-- Table: invoice_lines
CREATE TABLE IF NOT EXISTS invoice_lines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            invoice_id INTEGER NOT NULL,
            inventory_item_id INTEGER,
            item_name TEXT NOT NULL,
            quantity NUMERIC(18,2) DEFAULT 1,
            unit_price NUMERIC(18,2) DEFAULT 0,
            line_total NUMERIC(18,2) DEFAULT 0,
            cost_price NUMERIC(18,2) DEFAULT 0,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
            FOREIGN KEY (inventory_item_id) REFERENCES inventory(id) ON DELETE SET NULL
        );
-- INDEX idx_invoice_lines_inventory_item_id ON invoice_lines captured from inventory; definition requires manual review.
-- INDEX idx_invoice_lines_invoice_id ON invoice_lines captured from inventory; definition requires manual review.

-- Table: journal_lines
CREATE TABLE IF NOT EXISTS journal_lines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entry_id INTEGER NOT NULL,
            account_id INTEGER NOT NULL,
            debit NUMERIC(18,2) DEFAULT 0,
            credit NUMERIC(18,2) DEFAULT 0,
            FOREIGN KEY (entry_id) REFERENCES journal_entries(id) ON DELETE CASCADE,
            FOREIGN KEY (account_id) REFERENCES chart_of_accounts(id)
        );
-- INDEX idx_journal_lines_entry_account ON journal_lines captured from inventory; definition requires manual review.
-- INDEX idx_journal_lines_entry ON journal_lines captured from inventory; definition requires manual review.

-- Table: payment_allocations
CREATE TABLE IF NOT EXISTS payment_allocations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            payment_id INTEGER NOT NULL,
            invoice_id INTEGER,
            bill_id INTEGER,
            amount NUMERIC(18,2) DEFAULT 0,
            currency TEXT DEFAULT 'GHS',
            branch_id TEXT,
            created_by TEXT,
            allocated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (company_key) REFERENCES companies(key) ON DELETE CASCADE,
            FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE,
            FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
            FOREIGN KEY (bill_id) REFERENCES bills(id) ON DELETE CASCADE,
            FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE SET NULL
        );
-- INDEX idx_payment_allocations_bill ON payment_allocations captured from inventory; definition requires manual review.
-- INDEX idx_payment_allocations_invoice ON payment_allocations captured from inventory; definition requires manual review.
-- INDEX idx_payment_allocations_payment ON payment_allocations captured from inventory; definition requires manual review.

-- Table: pos_sale_lines
CREATE TABLE IF NOT EXISTS pos_sale_lines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            pos_sale_id INTEGER NOT NULL,
            company_key TEXT NOT NULL,
            inventory_item_id INTEGER,
            item_name TEXT NOT NULL,
            item_code TEXT,
            barcode TEXT,
            qty_sold NUMERIC(18,2) DEFAULT 0,
            unit_price NUMERIC(18,2) DEFAULT 0,
            line_discount NUMERIC(18,2) DEFAULT 0,
            tax_rate NUMERIC(18,2) DEFAULT 0,
            line_total NUMERIC(18,2) DEFAULT 0,
            cost_price NUMERIC(18,2) DEFAULT 0,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (pos_sale_id) REFERENCES pos_sales (id) ON DELETE CASCADE,
            FOREIGN KEY (company_key) REFERENCES companies (key) ON DELETE CASCADE
        );
-- INDEX idx_pos_sale_lines_item ON pos_sale_lines captured from inventory; definition requires manual review.
-- INDEX idx_pos_sale_lines_sale ON pos_sale_lines captured from inventory; definition requires manual review.

-- Table: recurring_transactions
CREATE TABLE IF NOT EXISTS recurring_transactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            branch_id TEXT,
            description TEXT NOT NULL,
            frequency TEXT NOT NULL,
            amount NUMERIC(18,2) DEFAULT 0,
            next_run_date TEXT NOT NULL,
            last_run_at TIMESTAMPTZ,
            is_active INTEGER DEFAULT 1,
            source_module TEXT,
            source_table TEXT,
            source_id INTEGER,
            created_by TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            recurrence_payload TEXT,
            FOREIGN KEY (company_key) REFERENCES companies(key) ON DELETE CASCADE,
            FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE SET NULL
        );
-- INDEX idx_recurring_transactions_next_run ON recurring_transactions captured from inventory; definition requires manual review.
-- INDEX idx_recurring_transactions_company ON recurring_transactions captured from inventory; definition requires manual review.

-- Table: stock_movements
CREATE TABLE IF NOT EXISTS stock_movements (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_key TEXT NOT NULL,
            branch_id TEXT,
            inventory_item_id INTEGER NOT NULL,
            item_name TEXT NOT NULL,
            movement_type TEXT NOT NULL,
            quantity NUMERIC(18,2) NOT NULL,
            reason TEXT,
            previous_qty NUMERIC(18,2) DEFAULT 0,
            new_qty NUMERIC(18,2) DEFAULT 0,
            created_by TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, posted_entry_id INTEGER, void_entry_id INTEGER, last_journal_sync_at TIMESTAMPTZ, status TEXT DEFAULT 'Draft', approval_status TEXT DEFAULT 'Draft', submitted_at TIMESTAMPTZ, approved_at TIMESTAMPTZ, approved_by TEXT, cancelled_at TIMESTAMPTZ, cancelled_by TEXT, reference TEXT, notes TEXT,
            FOREIGN KEY (inventory_item_id) REFERENCES inventory(id) ON DELETE CASCADE,
            FOREIGN KEY (company_key) REFERENCES companies(key) ON DELETE CASCADE,
            FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE SET NULL
        );
-- INDEX idx_stock_movements_item ON stock_movements captured from inventory; definition requires manual review.
-- INDEX idx_stock_movements_company_created ON stock_movements captured from inventory; definition requires manual review.

COMMIT;
