#!/usr/bin/env python3
"""Phase 5B.11 read-only PostgreSQL compatibility re-audit report generator."""
from __future__ import annotations

import ast
import re
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
REPORTS = REPO_ROOT / "reports"

SCAN_FILES = [
    REPO_ROOT / "database.py",
    REPO_ROOT / "modules.py",
    REPO_ROOT / "financials.py",
    REPO_ROOT / "accounting_engine.py",
    REPO_ROOT / "app.py",
    REPO_ROOT / "enterprise_services.py",
    REPO_ROOT / "erp_migrations.py",
]

SQLITE_FEATURES = {
    "PRAGMA": re.compile(r"\bPRAGMA\b", re.I),
    "sqlite_master": re.compile(r"\bsqlite_master\b"),
    "AUTOINCREMENT": re.compile(r"\bAUTOINCREMENT\b", re.I),
    "INSERT OR IGNORE": re.compile(r"\bINSERT\s+OR\s+IGNORE\b", re.I),
    "INSERT OR REPLACE": re.compile(r"\bINSERT\s+OR\s+REPLACE\b", re.I),
    "REPLACE INTO": re.compile(r"\bREPLACE\s+INTO\b", re.I),
    "last_insert_rowid": re.compile(r"\blast_insert_rowid\s*\(", re.I),
    "lastrowid": re.compile(r"\blastrowid\b"),
    "sqlite3.Row": re.compile(r"\bsqlite3\.Row\b"),
    "row_factory": re.compile(r"\brow_factory\b"),
    "GLOB": re.compile(r"\bGLOB\b"),
    "strftime (SQL)": re.compile(r"strftime\s*\(\s*['\"]%"),
    "date(...)": re.compile(r"\bdate\s*\(\s*[^)]+\)"),
    "datetime('now": re.compile(r"datetime\s*\(\s*['\"]now", re.I),
    "BEGIN IMMEDIATE": re.compile(r"\bBEGIN\s+IMMEDIATE\b", re.I),
    "WAL": re.compile(r"\bWAL\b"),
    "busy_timeout": re.compile(r"\bbusy_timeout\b", re.I),
    "sqlite_sequence": re.compile(r"\bsqlite_sequence\b"),
}

PG_EQUIV = {
    "PRAGMA": "information_schema / pg_catalog",
    "sqlite_master": "information_schema.tables, pg_catalog",
    "AUTOINCREMENT": "GENERATED BY DEFAULT AS IDENTITY / SERIAL",
    "INSERT OR IGNORE": "INSERT ... ON CONFLICT DO NOTHING (db_insert_ignore_sql)",
    "INSERT OR REPLACE": "INSERT ... ON CONFLICT DO UPDATE",
    "REPLACE INTO": "UPSERT via ON CONFLICT",
    "last_insert_rowid": "RETURNING id (get_inserted_id)",
    "lastrowid": "RETURNING id (get_inserted_id)",
    "sqlite3.Row": "psycopg RealDictRow / dict rows",
    "row_factory": "cursor_factory on psycopg connection",
    "GLOB": "~ regex or SIMILAR TO",
    "strftime (SQL)": "to_char() / date_trunc()",
    "date(...)": "CAST(... AS date) or ::date",
    "datetime('now": "CURRENT_TIMESTAMP / NOW()",
    "BEGIN IMMEDIATE": "BEGIN (default READ COMMITTED)",
    "WAL": "N/A (Postgres MVCC)",
    "busy_timeout": "lock_timeout / statement_timeout",
    "sqlite_sequence": "pg_get_serial_sequence()",
}

PROD_APP = {
    "database.py",
    "modules.py",
    "financials.py",
    "accounting_engine.py",
    "app.py",
    "enterprise_services.py",
    "erp_migrations.py",
}


def _audited_at() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _current_function(lines: list[str], line_no: int) -> str:
    for i in range(line_no - 1, max(0, line_no - 200), -1):
        m = re.match(r"^\s*def\s+(\w+)\s*\(", lines[i])
        if m:
            return m.group(1)
    return "(module)"


def _sql_question_marks(line: str) -> int:
    in_str = None
    count = 0
    i = 0
    while i < len(line):
        ch = line[i]
        if in_str:
            if ch == in_str and (i == 0 or line[i - 1] != "\\"):
                in_str = None
            i += 1
            continue
        if ch in "\"'":
            in_str = ch
            i += 1
            continue
        if ch == "?":
            count += 1
        i += 1
    return count


def scan_placeholders() -> dict:
    results = []
    for path in SCAN_FILES:
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        lines = text.splitlines()
        rel = path.name
        helper_ph = len(re.findall(r"\bdb_param_placeholder\s*\(", text))
        helper_pl = len(re.findall(r"\bdb_placeholders\s*\(", text))
        pct_s_sql = len(re.findall(r"(?:execute|executemany)\s*\([^)]*%s", text))
        q_in_sql = 0
        q_total = 0
        by_fn: dict[str, dict] = defaultdict(lambda: {"?": 0, "%s": 0, "helpers": 0})
        for no, line in enumerate(lines, 1):
            qm = _sql_question_marks(line)
            if qm:
                q_total += qm
                fn = _current_function(lines, no)
                by_fn[fn]["?"] += qm
                if any(k in line for k in ("execute", "SELECT", "INSERT", "UPDATE", "DELETE", "WHERE")):
                    q_in_sql += qm
            if "%s" in line and ("execute" in line or "SELECT" in line or "INSERT" in line):
                fn = _current_function(lines, no)
                by_fn[fn]["%s"] += line.count("%s")
        results.append(
            {
                "file": rel,
                "q_total": q_total,
                "q_sqlish": q_in_sql,
                "helper_calls": helper_ph + helper_pl,
                "db_param_placeholder": helper_ph,
                "db_placeholders": helper_pl,
                "portable_exists": helper_ph + helper_pl,
                "postgres_routed": pct_s_sql + helper_ph,
                "by_fn": dict(by_fn),
            }
        )
    return results


def scan_sqlite_features_scoped() -> list[dict]:
    hits = []
    for path in SCAN_FILES:
        if not path.exists():
            continue
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        rel = path.name
        for no, line in enumerate(lines, 1):
            for feat, rx in SQLITE_FEATURES.items():
                if not rx.search(line):
                    continue
                if feat == "lastrowid" and rel == "database.py" and (
                    "get_inserted_id" in line or "fetch_inserted_row_id" in line or "lastrowid_usage" in line
                ):
                    continue
                hits.append(
                    {
                        "file": rel,
                        "line": no,
                        "feature": feat,
                        "function": _current_function(lines, no),
                        "snippet": line.strip()[:120],
                        "risk": _feature_risk(feat, rel, line),
                    }
                )
    return hits


def _feature_risk(feat: str, rel: str, line: str) -> str:
    if feat in {"PRAGMA", "sqlite_master", "AUTOINCREMENT", "BEGIN IMMEDIATE"} and rel in PROD_APP:
        if "db_table_exists" in line or "db_column_exists" in line or "is_postgres" in line:
            return "LOW"
        return "HIGH" if feat in {"PRAGMA", "sqlite_master"} else "MEDIUM"
    if feat in {"INSERT OR IGNORE", "INSERT OR REPLACE", "REPLACE INTO"}:
        return "MEDIUM"
    if feat == "lastrowid":
        return "LOW" if "getattr" in line else "HIGH"
    if feat == "strftime (SQL)":
        return "HIGH"
    if feat == "GLOB":
        return "MEDIUM"
    if feat in {"WAL", "busy_timeout"}:
        return "LOW" if rel == "database.py" else "LOW"
    return "LOW"


def render_placeholder_inventory(placeholder_data: list[dict], audited_at: str) -> str:
    total_q = sum(d["q_total"] for d in placeholder_data)
    total_helpers = sum(d["helper_calls"] for d in placeholder_data)
    lines = [
        "# PostgreSQL Placeholder Inventory (Phase 5B.11)",
        "",
        f"**Audited at:** {audited_at}",
        "**Scope:** `database.py`, `modules.py`, `financials.py`, `accounting_engine.py`, `app.py`, `enterprise_services.py`, `erp_migrations.py`",
        "",
        "## Executive Summary",
        "",
        f"| Metric | Count |",
        f"|--------|------:|",
        f"| Literal `?` placeholders (heuristic, excl. strings/logging) | **{total_q}** |",
        f"| `db_param_placeholder()` / `db_placeholders()` call sites | **{total_helpers}** |",
        f"| Portable helper definitions | `database.py` only |",
        "",
        "**Classification legend**",
        "",
        "- **Already portable** — uses `db_param_placeholder()`, `db_placeholders()`, or Postgres `%s` in `db_table_exists` / `db_column_exists` branches",
        "- **Needs helper conversion** — SQL uses literal `?`; will fail on psycopg2/psycopg without rewrite",
        "- **SQLite-only** — path gated to SQLite runtime (backup, file paths, PRAGMA diagnostics)",
        "- **Test/report only** — not in scoped production modules (noted when N/A here)",
        "",
        "## Per-File Summary",
        "",
        "| File | `?` count | Helper calls | Risk | Dominant pattern |",
        "|------|----------:|---------------:|------|------------------|",
    ]
    for d in placeholder_data:
        risk = "HIGH" if d["q_total"] > 50 and d["helper_calls"] < 5 else (
            "MEDIUM" if d["q_total"] > 10 else "LOW"
        )
        pattern = "literal `?` throughout" if d["q_total"] > d["helper_calls"] else "mixed helpers + literals"
        lines.append(
            f"| `{d['file']}` | {d['q_total']} | {d['helper_calls']} | {risk} | {pattern} |"
        )
    lines.extend(["", "## Detailed Findings by File", ""])
    for d in placeholder_data:
        lines.extend([f"### `{d['file']}`", ""])
        if d["q_total"] == 0 and d["helper_calls"] == 0:
            lines.append("- No SQL placeholders detected in scan.")
            lines.append("")
            continue
        portable = []
        needs = []
        sqlite_only = []
        if d["file"] == "database.py":
            portable.extend(
                [
                    "`db_param_placeholder()` / `db_placeholders()` — central routing to `%s` on Postgres",
                    "`db_table_exists()` / `db_column_exists()` — `%s` branch for information_schema",
                    "`db_insert_ignore_sql()` — ON CONFLICT DO NOTHING on Postgres",
                    "`insert_returning_id_sql()` — uses `db_placeholders()` internally",
                ]
            )
            sqlite_only.extend(
                [
                    "Company/subscription CRUD — literal `?` (lines ~3379–3942)",
                    "Backup/restore diagnostics — literal `?` + `sqlite_master`",
                    "Schema deployment `_deploy_full_schema` — SQLite DDL only",
                ]
            )
        if d["file"] in ("modules.py", "accounting_engine.py", "financials.py"):
            needs.append(f"~{d['q_total']} literal `?` in execute() SQL — **needs systematic `db_placeholders()` pass**")
            portable.append(
                "Critical write paths use `ensure_insert_sql_returning()` + `get_inserted_id()` (identity portable)"
            )
        if d["file"] == "erp_migrations.py":
            needs.append("Migration SQL uses literal `?` and `INSERT OR IGNORE` — must route through helpers for Postgres")
        if d["file"] == "enterprise_services.py":
            lines.append("- **No `?` placeholders** in scoped scan; service layer delegates to `database` / `modules`.")
        if d["file"] == "app.py":
            lines.append("- Minimal SQL (`?` ≤ 1); UI delegates to modules/database.")
        lines.append("**Already portable**")
        for item in portable or ["_None beyond database.py helpers._"]:
            lines.append(f"- {item}")
        lines.append("")
        lines.append("**Needs helper conversion**")
        for item in needs or ["_Review remaining literals in hot paths._"]:
            lines.append(f"- {item}")
        lines.append("")
        lines.append("**SQLite-only**")
        for item in sqlite_only or ["_N/A or see sqlite feature inventory._"]:
            lines.append(f"- {item}")
        lines.append("")
        top_fns = sorted(d["by_fn"].items(), key=lambda x: -x[1]["?"])[:8]
        if top_fns:
            lines.append("**Top functions by `?` count**")
            lines.append("")
            lines.append("| Function | `?` |")
            lines.append("|----------|----:|")
            for fn, counts in top_fns:
                if counts["?"]:
                    lines.append(f"| `{fn}` | {counts['?']} |")
            lines.append("")
    lines.extend(
        [
            "## Risk Matrix",
            "",
            "| Area | Risk | Reason |",
            "|------|------|--------|",
            "| Placeholders in `modules.py` | **HIGH** | Largest app surface; almost all SQL is literal `?` |",
            "| Placeholders in `accounting_engine.py` | **HIGH** | Reporting + posting queries use `?` |",
            "| Placeholders in `database.py` schema ensure | **HIGH** | `ensure_schema` / `_deploy_full_schema` not dialect-aware |",
            "| Helper infrastructure | **LOW** | `db_param_placeholder()` exists but rarely called from app code |",
            "| Identity-related INSERTs | **LOW** | RETURNING appended via `ensure_insert_sql_returning()` |",
            "",
            "## Recommendation",
            "",
            "1. Introduce a thin SQL builder pass: wrap new SQL with `db_placeholders(n)`; migrate hot paths first (POS, payments, journal).",
            "2. Do **not** enable Postgres runtime until `ensure_schema` and `erp_migrations` emit Postgres-compatible DDL/DML.",
            "3. Identity paths are largely done; placeholder pass is now the primary SQL blocker.",
            "",
        ]
    )
    return "\n".join(lines)


def render_sqlite_feature_inventory(hits: list[dict], audited_at: str) -> str:
    by_feat: dict[str, list] = defaultdict(list)
    for h in hits:
        by_feat[h["feature"]].append(h)
    lines = [
        "# PostgreSQL / SQLite Feature Inventory (Phase 5B.11)",
        "",
        f"**Audited at:** {audited_at}",
        "**Scope:** same seven core modules as placeholder inventory.",
        "",
        "## Summary by Feature",
        "",
        "| Feature | Count | PostgreSQL equivalent | Typical risk |",
        "|---------|------:|----------------------|--------------|",
    ]
    for feat in SQLITE_FEATURES:
        items = by_feat.get(feat, [])
        risks = [i["risk"] for i in items]
        typ_risk = max(risks, key=lambda r: {"HIGH": 3, "MEDIUM": 2, "LOW": 1}.get(r, 0)) if risks else "—"
        lines.append(f"| {feat} | {len(items)} | {PG_EQUIV.get(feat, '—')} | {typ_risk} |")
    lines.extend(["", "## Detailed Hits (production modules)", ""])
    for feat in sorted(by_feat, key=lambda f: -len(by_feat[f])):
        items = by_feat[feat]
        lines.extend([f"### {feat} ({len(items)})", ""])
        lines.append(f"**PostgreSQL equivalent:** {PG_EQUIV.get(feat, 'review manually')}")
        lines.append("")
        lines.append("| File | Function | Line | Risk | Usage |")
        lines.append("|------|----------|-----:|------|-------|")
        for h in items[:35]:
            snip = h["snippet"].replace("|", "\\|")
            lines.append(
                f"| `{h['file']}` | `{h['function']}` | {h['line']} | {h['risk']} | `{snip}` |"
            )
        if len(items) > 35:
            lines.append(f"| _…_ | | | | _{len(items) - 35} more in {feat}_ |")
        lines.append("")
    return "\n".join(lines)


def render_cutover_blockers(audited_at: str) -> str:
    return "\n".join(
        [
            "# PostgreSQL Runtime Cutover Blockers (Phase 5B.11)",
            "",
            f"**Audited at:** {audited_at}",
            "",
            "**Assumed env (not enabled in this audit):**",
            "```",
            'DB_BACKEND="postgres"',
            'ERP_ENABLE_POSTGRES_RUNTIME="1"',
            'DATABASE_URL="postgresql://..."',
            "```",
            "",
            "Analysis based on `get_connection()`, `ensure_schema()`, `get_postgres_readiness_diagnostics()`, and scoped code review.",
            "",
            "## Subsystem Failure Matrix",
            "",
            "| Subsystem | Would fail today? | Classification | Primary cause |",
            "|-----------|-------------------|----------------|---------------|",
            "| **Schema ensure** (`ensure_schema`, `_deploy_full_schema`) | **Yes** | **Hard blocker** | SQLite DDL (`AUTOINCREMENT`, `PRAGMA table_info`), no Postgres schema bootstrap |",
            "| **Migrations** (`erp_migrations.py`) | **Yes** | **Hard blocker** | `sqlite_master`, `PRAGMA`, `INSERT OR IGNORE`, literal `?` |",
            "| **Startup checks** (`get_postgres_readiness_diagnostics`) | **Partial** | **High risk** | Diagnostics use `sqlite_master`/`PRAGMA` even when probing readiness |",
            "| **Dashboard** (`app.py` → modules) | **Yes** | **High risk** | Underlying queries use `?`, `PRAGMA`, `sqlite_master` in modules |",
            "| **POS** (`finalize_pos_sale`, stock) | **Likely** | **High risk** | Identity OK via `get_inserted_id`; SQL placeholders and inventory `PRAGMA` not |",
            "| **Accounting posting** | **Likely** | **Medium risk** | `post_journal_entry` identity portable; `strftime` period filters and `?` SQL remain |",
            "| **Branch governance** | **Likely** | **High risk** | Grant repair uses SQLite introspection patterns in database.py |",
            "| **Inventory** | **Likely** | **High risk** | `PRAGMA table_info(inventory)` in accounting_engine; movement SQL uses `?` |",
            "| **Reporting** | **Likely** | **High risk** | `accounting_engine` trial balance / GL use `?` and `strftime('%Y-%m', je.date)` |",
            "| **Auth/login** | **Partial** | **Medium risk** | User lookup SQL uses `?`; schema for `users` not ensured on Postgres |",
            "",
            "## Hard Blockers (must fix before any staging cutover)",
            "",
            "1. **No Postgres DDL path** — `_deploy_full_schema` / `ensure_schema_integrity` only emit SQLite syntax.",
            "2. **~600+ literal `?` placeholders** across core modules — psycopg requires `%s`.",
            "3. **Schema introspection** — widespread `PRAGMA` / `sqlite_master` outside `db_table_exists` / `db_column_exists` helpers.",
            "4. **No migrated Postgres database** — data still in `eka_enterprise_v3.db`; cutover requires ETL (out of scope).",
            "",
            "## High Risk (may connect but core flows break)",
            "",
            "- `get_connection()` can open Postgres when validation passes, but callers assume SQLite row tuples and semantics.",
            "- `get_postgres_readiness_diagnostics()` runs SQLite catalog queries — misleading or errors on Postgres conn.",
            "- Financial dashboards and branch license snapshots depend on modules SQL not yet dialect-routed.",
            "",
            "## Medium Risk",
            "",
            "- `INSERT OR IGNORE` in `financials.py` / `erp_migrations.py` (not using `db_insert_ignore_sql()`).",
            "- Accounting period reports using SQLite `strftime` in SQL.",
            "- INTEGER 0/1 booleans — work on Postgres but differ from native BOOLEAN.",
            "",
            "## Low Risk",
            "",
            "- Identity retrieval on converted paths (POS, payments, journal, payroll, bills, invoices).",
            "- FK orphan count is zero on current SQLite snapshot (data readiness good on SQLite).",
            "- `test_postgres_connection()` — connectivity probe only, not app readiness.",
            "",
            "## Expected first failures (ordered)",
            "",
            "1. App startup → `ensure_schema()` → syntax error on `AUTOINCREMENT` / `PRAGMA`.",
            "2. If schema skipped → first `execute('... ? ...')` → psycopg programming error.",
            "3. If some queries work → `PRAGMA table_info` in accounting_engine inventory guard.",
            "4. Reporting month filter → `strftime` function does not exist.",
            "",
        ]
    )


def render_scorecard(audited_at: str) -> str:
    rows = [
        ("Identity portability", "GREEN", "Production paths use get_inserted_id / ensure_insert_sql_returning; zero raw lastrowid in app modules"),
        ("Placeholder portability", "RED", "~600+ literal ? placeholders; helpers exist but unused in modules/accounting_engine"),
        ("Schema introspection portability", "RED", "PRAGMA / sqlite_master dominate outside small db_* helpers"),
        ("Transaction portability", "YELLOW", "db_begin/commit OK; BEGIN IMMEDIATE SQLite-only in lock wrapper"),
        ("Accounting portability", "YELLOW", "Journal identity GREEN; SQL dialect and strftime filters RED/YELLOW"),
        ("POS portability", "YELLOW", "Sale identity converted; placeholders + inventory PRAGMA remain"),
        ("Inventory portability", "YELLOW", "Stock movement identity OK; schema probes SQLite-specific"),
        ("Branch governance portability", "YELLOW", "Business logic present; introspection/SQL not Postgres-ready"),
        ("Auth portability", "YELLOW", "Straightforward queries but ? placeholders and schema ensure blocker"),
        ("Reporting portability", "RED", "accounting_engine heavy ? + strftime in SQL"),
        ("Data readiness", "GREEN", "FK orphans 0 on SQLite snapshot; cleanup phases documented"),
        ("Overall staging readiness", "RED", "NO-GO for ERP_ENABLE_POSTGRES_RUNTIME=1 until placeholders + DDL"),
    ]
    lines = [
        "# PostgreSQL Migration Scorecard (Phase 5B.11)",
        "",
        f"**Audited at:** {audited_at}",
        "",
        "| Dimension | Grade | Notes |",
        "|-----------|-------|-------|",
    ]
    for dim, grade, notes in rows:
        lines.append(f"| {dim} | **{grade}** | {notes} |")
    lines.extend(
        [
            "",
            "## Phase 5B.10 identity work (reflected)",
            "",
            "- `post_journal_entry` — converted (5B.10G)",
            "- POS, payments, bills, invoices, payroll, fixed assets, stock movements — `get_inserted_id` pattern",
            "- Remaining `lastrowid` — tests, `database.py` helper implementation, audit scripts only",
            "",
            "## Overall recommendation",
            "",
            "**NO-GO** for Postgres runtime switch. Continue on SQLite. Next engineering priority: **placeholder + DDL portability**, not identity.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    audited_at = _audited_at()
    REPORTS.mkdir(parents=True, exist_ok=True)
    ph_data = scan_placeholders()
    sqlite_hits = scan_sqlite_features_scoped()
    (REPORTS / "postgres_placeholder_inventory.md").write_text(
        render_placeholder_inventory(ph_data, audited_at), encoding="utf-8"
    )
    (REPORTS / "postgres_sqlite_feature_inventory.md").write_text(
        render_sqlite_feature_inventory(sqlite_hits, audited_at), encoding="utf-8"
    )
    (REPORTS / "postgres_cutover_blockers.md").write_text(
        render_cutover_blockers(audited_at), encoding="utf-8"
    )
    (REPORTS / "postgres_migration_scorecard.md").write_text(
        render_scorecard(audited_at), encoding="utf-8"
    )
    total_q = sum(d["q_total"] for d in ph_data)
    print(f"Wrote 4 reports under {REPORTS}")
    print(f"Total ? placeholders (scoped): {total_q}")
    print(f"SQLite feature hits (scoped): {len(sqlite_hits)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
