MASTER_KEY = "JUANMANUEL2"
DB_NAME = "eka_vault.db"
PAYSTACK_SECRET_KEY = "sk_test_xxxxxxxxxxxx"
OPENAI_API_KEY = "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"